# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "android"
    target-branch: "main"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "code-samples/ARBlackPanther"
    target-branch: "main"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "code-samples/ARHelloWorldAndroid"
    target-branch: "main"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "code-samples/ARPlacingObjects"
    target-branch: "main"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "code-samples/ARRetail"
    target-branch: "main"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "code-samples/ARTesla"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    target-branch: "main"
    schedule:
      interval: "weekly"